// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYYGj-PNS-P4jcMp00BN3EXzYKqZ-WGws',
    appId: '1:471821678431:web:426ca40330b7c219c3e8ea',
    messagingSenderId: '471821678431',
    projectId: 'testing-bc269',
    authDomain: 'testing-bc269.firebaseapp.com',
    storageBucket: 'testing-bc269.firebasestorage.app',
    measurementId: 'G-753Z608MS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKt23YsSnjjO_h-9SUrYwEytxvu4xd1R8',
    appId: '1:471821678431:android:3efee90b5a2a5029c3e8ea',
    messagingSenderId: '471821678431',
    projectId: 'testing-bc269',
    storageBucket: 'testing-bc269.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgv4pzrcMSm7dafCoaPvumTv4dMu8z-Rg',
    appId: '1:471821678431:ios:965827380325b153c3e8ea',
    messagingSenderId: '471821678431',
    projectId: 'testing-bc269',
    storageBucket: 'testing-bc269.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgv4pzrcMSm7dafCoaPvumTv4dMu8z-Rg',
    appId: '1:471821678431:ios:965827380325b153c3e8ea',
    messagingSenderId: '471821678431',
    projectId: 'testing-bc269',
    storageBucket: 'testing-bc269.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYYGj-PNS-P4jcMp00BN3EXzYKqZ-WGws',
    appId: '1:471821678431:web:3c0462dcd5aeb83cc3e8ea',
    messagingSenderId: '471821678431',
    projectId: 'testing-bc269',
    authDomain: 'testing-bc269.firebaseapp.com',
    storageBucket: 'testing-bc269.firebasestorage.app',
    measurementId: 'G-QD53N4048X',
  );
}
