import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _language = 'en';

  String get language => _language;
  bool get isSwahili => _language == 'sw';

  LanguageProvider();

  // Call this before runApp to ensure language is loaded synchronously
  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _language = prefs.getString('language') ?? 'en';
  }

  Future<void> setLanguage(String lang) async {
    _language = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', lang);
    notifyListeners();
  }

  String t(String key) {
    return _translations[_language]?[key] ?? _translations['en']![key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // Login
      'welcome_back': 'Welcome Back',
      'your_marketplace': 'Your fresh seafood marketplace.\nLogin to continue.',
      'enter_email': 'Enter your email',
      'password': 'Password',
      'remember_me': 'Remember me',
      'forget_password': 'Forget Password',
      'login': 'Login',
      'no_account': "Don't have an account? ",
      'register': 'Register',

      // Register
      'create_account': 'Create Account',
      'sign_up': 'Sign up to get started',
      'full_name': 'Full Name',
      'username': 'Username',
      'phone': 'Phone Number',
      'email': 'Email',
      'confirm_password': 'Confirm Password',
      'already_account': 'Already have an account? ',
      'customer': 'Customer',
      'seller': 'Seller',
      'driver': 'Driver',
      'passwords_no_match': 'Passwords do not match',
      'reg_success': 'Registration successful! Please login.',
      'reg_failed': 'Registration failed: ',

      // Forgot password
      'reset_password': 'Reset Password',
      'reset_subtitle': "Enter your email and we'll send you a reset link",
      'send_reset': 'Send Reset Link',
      'back_login': 'Back to Login',
      'email_sent': 'Email Sent!',
      'resend': 'Resend Email',
      'next_steps': 'Next steps:',
      'step1': 'Open your email inbox',
      'step2': 'Click the reset link in the email',
      'step3': 'Set your new password',
      'step4': 'Come back and login',

      // Dashboards
      'welcome': 'Welcome',
      'customer_account': 'Customer Account',
      'seller_account': 'Seafood Seller Account',
      'driver_account': 'Delivery Driver',
      'logout': 'Logout',
      'browse_seafood': 'Browse Seafood',
      'my_orders': 'My Orders',
      'favorites': 'Favorites',
      'my_profile': 'My Profile',
      'add_product': 'Add Product',
      'my_products': 'My Products',
      'orders': 'Orders',
      'sales_report': 'Sales Report',
      'available_orders': 'Available Orders',
      'active_delivery': 'Active Delivery',
      'delivery_history': 'Delivery History',
      'earnings': 'Earnings',
      'online': 'You are Online',
      'offline': 'You are Offline',
      'coming_soon': 'Coming Soon',
      'dashboard': 'Dashboard',
      'quick_actions': 'Quick Actions',
      'offers': 'Offers',
      'support': 'Support',
      'search_products': 'Search products...',
      'sort_by': 'Sort by',
      'status': 'Status',
      'newest': 'Newest',
      'oldest': 'Oldest',
      'price_high': 'Price ↑',
      'price_low': 'Price ↓',
      'name_az': 'Name A-Z',
      'all': 'All',
      'active': 'Active',
      'inactive': 'Inactive',
      'no_products': 'No products yet. Tap + to add one.',
      'no_match': 'No products match your search.',
      'deactivate': 'Deactivate',
      'delete': 'Delete',
      'activate': 'Activate',
      'delete_confirm': 'Are you sure you want to delete this product?',
      'cancel': 'Cancel',
      'delete_product': 'Delete Product',
      'stock': 'Stock',
      'product_name': 'Product Name',
      'description': 'Description',
      'category': 'Category',
      'price_tzs': 'Price (TShs)',
      'unit': 'Unit',
      'available_stock': 'Available Stock',
      'pickup_location': 'Pickup Location',
      'product_details': 'Product Details',
      'pricing_stock': 'Pricing & Stock',
      'location': 'Location',
      'select_image': 'Tap to add product photo',
      'select_source': 'Select Image Source',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'product_added': 'Product added successfully!',
      'select_image_error': 'Please select a product image',
      'full_name_label': 'Full Name',
      'phone_label': 'Phone',
      'email_label': 'Email',
      // Categories
      'cat_fish': 'Fish',
      'cat_shrimp': 'Shrimp',
      'cat_crab': 'Crab',
      'cat_lobster': 'Lobster',
      'cat_squid': 'Squid',
      'cat_octopus': 'Octopus',
      'cat_other': 'Other',
      // Units
      'unit_kg': 'kg',
      'unit_g': 'g',
      'unit_piece': 'piece',
      'unit_dozen': 'dozen',
    },
    'sw': {
      // Login
      'welcome_back': 'Karibu Tena',
      'your_marketplace': 'Soko lako la samaki safi.\nIngia kuendelea.',
      'enter_email': 'Ingiza barua pepe yako',
      'password': 'Nywila',
      'remember_me': 'Nikumbuke',
      'forget_password': 'Umesahau Nywila',
      'login': 'Ingia',
      'no_account': 'Huna akaunti? ',
      'register': 'Jisajili',

      // Register
      'create_account': 'Fungua Akaunti',
      'sign_up': 'Jisajili kuanza',
      'full_name': 'Jina Kamili',
      'username': 'Jina la Mtumiaji',
      'phone': 'Nambari ya Simu',
      'email': 'Barua Pepe',
      'confirm_password': 'Thibitisha Nywila',
      'already_account': 'Una akaunti tayari? ',
      'customer': 'Mteja',
      'seller': 'Muuzaji',
      'driver': 'Dereva',
      'passwords_no_match': 'Nywila hazifanani',
      'reg_success': 'Usajili umefanikiwa! Tafadhali ingia.',
      'reg_failed': 'Usajili umeshindwa: ',

      // Forgot password
      'reset_password': 'Weka Upya Nywila',
      'reset_subtitle':
          'Ingiza barua pepe yako na tutakutumia kiungo cha kuweka upya',
      'send_reset': 'Tuma Kiungo',
      'back_login': 'Rudi Kuingia',
      'email_sent': 'Barua Pepe Imetumwa!',
      'resend': 'Tuma Tena',
      'next_steps': 'Hatua zinazofuata:',
      'step1': 'Fungua kisanduku chako cha barua pepe',
      'step2': 'Bonyeza kiungo cha kuweka upya',
      'step3': 'Weka nywila yako mpya',
      'step4': 'Rudi na uingie',

      // Dashboards
      'welcome': 'Karibu',
      'customer_account': 'Akaunti ya Mteja',
      'seller_account': 'Akaunti ya Muuzaji wa Samaki',
      'driver_account': 'Dereva wa Utoaji',
      'logout': 'Toka',
      'browse_seafood': 'Tazama Samaki',
      'my_orders': 'Maagizo Yangu',
      'favorites': 'Vipendwa',
      'my_profile': 'Wasifu Wangu',
      'add_product': 'Ongeza Bidhaa',
      'my_products': 'Bidhaa Zangu',
      'orders': 'Maagizo',
      'sales_report': 'Ripoti ya Mauzo',
      'available_orders': 'Maagizo Yanayopatikana',
      'active_delivery': 'Utoaji Unaoendelea',
      'delivery_history': 'Historia ya Utoaji',
      'earnings': 'Mapato',
      'online': 'Uko Mtandaoni',
      'offline': 'Uko Nje ya Mtandao',
      'coming_soon': 'Inakuja Hivi Karibuni',
      'dashboard': 'Dashibodi',
      'quick_actions': 'Vitendo vya Haraka',
      'offers': 'Ofa',
      'support': 'Msaada',
      'search_products': 'Tafuta bidhaa...',
      'sort_by': 'Panga kwa',
      'status': 'Hali',
      'newest': 'Mpya Zaidi',
      'oldest': 'Kongwe Zaidi',
      'price_high': 'Bei ↑',
      'price_low': 'Bei ↓',
      'name_az': 'Jina A-Z',
      'all': 'Zote',
      'active': 'Inafanya Kazi',
      'inactive': 'Haifanyi Kazi',
      'no_products': 'Hakuna bidhaa bado. Bonyeza + kuongeza.',
      'no_match': 'Hakuna bidhaa zinazolingana na utafutaji wako.',
      'deactivate': 'Zima',
      'delete': 'Futa',
      'activate': 'Washa',
      'delete_confirm': 'Una uhakika unataka kufuta bidhaa hii?',
      'cancel': 'Ghairi',
      'delete_product': 'Futa Bidhaa',
      'stock': 'Hisa',
      'product_name': 'Jina la Bidhaa',
      'description': 'Maelezo',
      'category': 'Aina',
      'price_tzs': 'Bei (TShs)',
      'unit': 'Kipimo',
      'available_stock': 'Hisa Inayopatikana',
      'pickup_location': 'Mahali pa Kuchukua',
      'product_details': 'Maelezo ya Bidhaa',
      'pricing_stock': 'Bei na Hisa',
      'location': 'Mahali',
      'select_image': 'Gusa kuongeza picha ya bidhaa',
      'select_source': 'Chagua Chanzo cha Picha',
      'camera': 'Kamera',
      'gallery': 'Matunzio',
      'product_added': 'Bidhaa imeongezwa!',
      'select_image_error': 'Tafadhali chagua picha ya bidhaa',
      'full_name_label': 'Jina Kamili',
      'phone_label': 'Simu',
      'email_label': 'Barua Pepe',
      // Categories
      'cat_fish': 'Samaki',
      'cat_shrimp': 'Kamba',
      'cat_crab': 'Kaa',
      'cat_lobster': 'Kamba Kochi',
      'cat_squid': 'Ngisi',
      'cat_octopus': 'Pweza',
      'cat_other': 'Nyingine',
      // Units
      'unit_kg': 'kg',
      'unit_g': 'g',
      'unit_piece': 'kipande',
      'unit_dozen': 'dazeni',
    },
  };
}
